apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-consumer
rules:
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "patch"




