apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: kinf
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: consumer
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: consumer-service-account
      containers:
      - name: consumer
        image: wdalmut/consumer
        env:
          - name: REDIS_HOST
            value: "queue-service"
          - name: GET_QUEUE_NAME
            value: 'add-pods'
          - name: PROCESSING_QUEUE_NAME
            value: 'add-pods-processing'
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "128m"


